# IO
library_path: /raid/passive
db_path: /app/embeddings.db
model_path: /models/discogs-effnet-bs64-1.pb
output_m3u: /app/nightwave.m3u
audio_formats:
  - mp3
  - flac

# Misc
num_anchors: 10
interpolation_count: 10
interpolation_mode: diverse
allow_anchors_in_pool: true
fuzzy_match_threshold: 0.6
loop: true

# Diverse 
diverse_curve_power: 0.9
diverse_candidates: 20
diverse_artist_window: 3
diverse_artist_penalty: 0.35

# Azuracast
azuracast:
  url: "http://192.168.1.143"
  api_key: "809ef913c5b4fbfa:d8aea327393dec3c7431d1565170400d"
  station_id: 4
  playlist_id: 2

# Anchors
anchor_songs: 
  -"Diablo II Resurrected - Tristram"
  -"Etrian Odyssey I HD - Dungeon 2"
  -"Etrian Odyssey I HD - Dungeon 3"
  -"Etrian Odyssey I HD - Dungeon 4"
  -"Etrian Odyssey I HD - Dungeon 5"
  -"Hollow Knight - Dirtmouth"
  -"Hollow Knight - Crystal Peak"
  -"Hollow Knight - City of Tears"
  -"Metroid Prime - Crashed Frigate Orpheon"
  -"Wild Arms Alter Code-F - The Elw Dimension"
anchor_artists: []
anchor_albums: []
anchor_genres: []

# Exclude
exclude_songs: []
exclude_artists: []
exclude_albums: []
exclude_genres: []
